spring:
  application:
    name: toolsly
  config:
    import: optional:file:.env[.properties]
  datasource:
    # Most properties are loaded from .env
    # Default values for local development if .env is missing
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25
        lob:
          non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: 86400000 # 1 day

server:
  port: ${PORT:8080}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %thread | %-5level | %logger{36} | %msg%n"
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.duwniy.toolsly: INFO
    root: INFO
