UPDATE users SET created_at = NOW() WHERE created_at IS NULL;
UPDATE orders SET created_at = NOW() WHERE created_at IS NULL;

ALTER TABLE users 
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE, 
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE orders 
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE, 
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE, 
    ALTER COLUMN planned_end_date TYPE TIMESTAMP WITH TIME ZONE, 
    ALTER COLUMN actual_end_date TYPE TIMESTAMP WITH TIME ZONE, 
    ALTER COLUMN reserved_until TYPE TIMESTAMP WITH TIME ZONE, 
    ALTER COLUMN issued_at TYPE TIMESTAMP WITH TIME ZONE;
